[package]
name = "windmill"
version = "0.1.0"
authors = ["Dunja Lalic"]
edition = "2021"

[dependencies]
piston = "0.53.1"
piston2d-graphics = "0.42.0"
pistoncore-glutin_window = "0.70.0"
piston2d-opengl_graphics = "0.81.0"
