[package]
name = "windmill"
version = "0.1.0"
authors = ["Dunja Lalic"]
edition = "2018"

[dependencies]
piston = "0.51"
piston2d-graphics = "0.36"
pistoncore-glutin_window = "0.66"
piston2d-opengl_graphics = "0.72"
